services:
  solara-music:
    image: aexus/solara-music:latest
    container_name: solara-music
    restart: unless-stopped
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - SOLARA_PASSWORD=111  # 修改为你的密码
      - SESSION_SECRET=KLmlKDruIBRYjrT5ct7B3xqG25ZF2p593333    # 修改为随机字符串
    volumes:
      - ./logs:/app/logs